### ISSUE TITLE
Fix formatting of readme

### ISSUE THREAD

**Issue by Roshanjossey** [nickdesaulniers/What-Open-Source-Means-To-Me#91]
Currently the readme doesn't use markdown formatting correctly.

For example, rather than using

# What Open Source Means To Me

We're using

#What Open Source Means To Me

I believe using correct formatting would improve readability a lot.

I'd like to open a PR to fix this if you wanna take this forward

**Comment by justinclift** [comment]
@Roshanjossey Ahhh, that's interesting.  It definitely used to render in a visually proper way.

But, it's not now.  Maybe related to GitHub's recent [spec definition of GitHub Flavoured Markdown](https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown).

If you do a PR with the formatting fixed, I can definitely merge it. :smile:

**Comment by Roshanjossey** [comment]
@justinclift: I'm on it.
